### PR TITLE
Changes to Project 2 README and notebooks

### PR DESCRIPTION
**Pull request by robroc**
I expanded the Project 2 README and made the code more consistent with the notebook. I also added more to the JSON section.

I also explained the differences between opening a file and using `with` to let Python handle the file closing.

A few minor changes to the notebook, mostly removed the binary option when opening a file, which is no longer necessary in Python 3.

### CODE REVIEW

**Comment by tommeagher** [comment]
This PR is against the wrong repo. We sunset https://github.com/tommeagher/pycar14 a few years ago. Can you send the PR to the master branch of https://github.com/ireapps/pycar?

**Comment by robroc** [comment]
Ah crap I don't know how this happened. I thought I cloned the one from @ireapps. It was my first PR ever, so I'm still a bit fuzzy on the whole branch rigamarole. I'll fix this.

**Comment by robroc** [comment]
@tommeagher I'm confused, when I try to do a PR to ireapps/pycar it redirects me to your repo each time. Can you help a stumped brother out?

**Comment by tommeagher** [comment]
Ahhh, I see what happened now. You already put all the changes directly into the master branch on the main repo: https://github.com/ireapps/pycar
Normally what you'd want to do is create a new branch on that repo for a specific feature, like "documentation," and then send a pull request to merge that feature branch into the master branch. That PR then allows other collaborators to review changes and give feedback. I glanced at your changes and they look great to me, so since they're already in the master branch, we should be all set. Thanks!

**Pull request closed without merging**
